---
- name: Ensure the target directory exists
  file:
    path: /var/www/html/images
    state: directory
    mode: '0755'
    owner: www-data
    group: www-data

- name: Copy images to the server
  copy:
    src: "{{ item }}"
    dest: /var/www/html/images/
    owner: www-data
    group: www-data
    mode: '0644'
  with_fileglob:
    - "{{ playbook_dir }}/roles/static_image_upload/files/*"
